#application: snowpero
#version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /telegram_bot/.*
  script: telegram_bot.app
- url: /.*
  script: main.app
- url: /task/.*
  script: main.app
